{
 "title": "Libvirt Dashboard",
 "description": "A simple dashboard that can monitor libvirt KVM",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,30s,1m,2m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{job=\"libvirt_exporter\"}, host)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_state_code{host=\"$compute\", job=\"libvirt_exporter\"}, domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Libvirt Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domains_number{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"libvirt_exporter\"} ==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"libvirt_exporter\"} ==5)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "vCPU Usage on VM",
   "type": "timeseries",
   "description": "100% = 1 Thread",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])) * 100",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "No State VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"libvirt_exporter\"} ==0)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Suspend VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"libvirt_exporter\"} ==3)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Crashed VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{host=~\"$compute\", job=~\"libvirt_exporter\"} ==6)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_state_code{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"})",
     "legendFormat": "VM State"
    }
   ]
  },
  {
   "title": "Total vCPU on VM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "IOPS R/W on VM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Throughput R/W on VM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "Memory on VM",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "libvirt_domain_stat_memory_unused_bytes{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"} - libvirt_domain_stat_memory_unused_bytes{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RX/TX Throughput on VM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "RX/TX Packets Drop on VM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$virtual_machine\", host=~\"$compute\", job=~\"libvirt_exporter\"}[30s]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "vCPU Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "vCPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])) * 100",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_unused_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"} - libvirt_domain_stat_memory_unused_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Resident Set Size",
   "type": "timeseries",
   "description": "Resident Set Size of the process running the domain, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_rss_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Swap Read",
   "type": "timeseries",
   "description": "The total amount of data read from swap space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_swap_in_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Swap Written",
   "type": "timeseries",
   "description": "The total amount of memory written out to swap space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_swap_out_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_requests_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_write_requests_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_bytes_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_write_bytes_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{target_device}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_bytes_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_bytes_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "RX Packets",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_packets_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "timeseries",
   "description": "Number of packets transmitted on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "RX Packets Error",
   "type": "timeseries",
   "description": "Number of packet receive errors on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_errors_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "TX Packets Error",
   "type": "timeseries",
   "description": "Number of packet transmit errors on a network interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "RX Packets Drop",
   "type": "timeseries",
   "description": "Number of packet receive drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  {
   "title": "TX Packets Drop",
   "type": "timeseries",
   "description": "Number of packet transmit drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])",
     "legendFormat": "{{domain}} - {{source_bridge}}"
    }
   ]
  },
  { "title": "Data Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{host=~\"$compute\", job=~\"libvirt_exporter\"}-0",
     "legendFormat": "vCPU Total"
    },
    {
     "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{host=~\"$compute\", job=~\"libvirt_exporter\"}[30s])) * 100)-0",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"}-0",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"} - libvirt_domain_stat_memory_unused_bytes{host=~\"$compute\", job=~\"libvirt_exporter\"})-0",
     "legendFormat": "Memory Used"
    }
   ]
  }
 ]
}