{
 "title": "Battery",
 "description": "UPS and EcoFlow battery telemetry",
 "tags": [
  "battery",
  "ups",
  "ecoflow",
  "electricity",
  "IoT"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(network_ups_tools_device_info,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(network_ups_tools_device_info,job)"
    }
   },
   {
    "name": "ups",
    "label": "UPS",
    "query": "label_values(network_ups_tools_device_info,ups)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecoflow_online, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "UPS: $ups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ups" },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{mfr}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Run Time Left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Line Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "network_ups_tools_battery_voltage_low{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "voltage"
    },
    {
     "expr": "network_ups_tools_battery_voltage_high{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "voltage"
    },
    {
     "expr": "network_ups_tools_battery_voltage_high{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "voltage"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    },
    {
     "expr": "network_ups_tools_battery_voltage_low{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "voltage"
    },
    {
     "expr": "network_ups_tools_battery_voltage_high{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}*1.1",
     "legendFormat": "voltage"
    },
    {
     "expr": "network_ups_tools_battery_voltage_high{instance=~\"$instance\",job=~\"$job\",ups=\"$ups\"}",
     "legendFormat": "voltage"
    }
   ]
  },
  { "title": "EcoFlow: $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "device" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_online{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_vol{device=\"$device\"} or ecoflow_inv_inv_in_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_amp{device=\"$device\"} or ecoflow_inv_inv_in_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Charging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_ems_chg_remain_time{device=\"$device\"} or ecoflow_bms_ems_status_chg_remain_time{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Full Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_full_cap{device=\"$device\"} or ecoflow_bms_bms_status_full_cap{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "BMS Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(ecoflow_bms_master_amp{device=\"$device\"}) or abs(ecoflow_bms_bms_status_amp{device=\"$device\"})"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol{device=\"$device\"} or ecoflow_bms_bms_status_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MIN Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MAX Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_f32_show_soc{device=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{device=\"$device\"} or ecoflow_bms_master_soc{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_output_watts{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Discharging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_ems_dsg_remain_time{device=\"$device\"} or ecoflow_bms_ems_status_dsg_remain_time{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Remain Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_remain_cap{device=\"$device\"} or ecoflow_bms_bms_status_remain_cap{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_cycles{device=\"$device\"} or ecoflow_bms_bms_status_cycles{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_out_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MIN Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_temp{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MAX Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_temp{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_amp{device=\"$device\"} or ecoflow_bms_bms_status_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_soc{device=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{device=\"$device\"}",
     "legendFormat": "Battery Level"
    }
   ]
  },
  {
   "title": "I/O Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{device=\"$device\"}",
     "legendFormat": "Input Watts"
    },
    {
     "expr": "ecoflow_inv_output_watts{device=\"$device\"}",
     "legendFormat": "Output Watts"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "abs(ecoflow_ems_chg_remain_time{device=\"$device\"}) or abs(ecoflow_bms_ems_status_chg_remain_time{device=\"$device\"}) ",
     "legendFormat": "Charging Remain Time"
    },
    {
     "expr": "abs(ecoflow_ems_dsg_remain_time{device=\"$device\"}) or abs(ecoflow_bms_ems_status_dsg_remain_time{device=\"$device\"})",
     "legendFormat": "Discharging Remain Time"
    }
   ]
  },
  {
   "title": "I/O Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_vol{device=\"$device\"} > 0",
     "legendFormat": "Inverter In"
    },
    {
     "expr": "ecoflow_inv_inv_out_vol{device=\"$device\"} > 0",
     "legendFormat": "Inverter Out"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_inv_out_temp{device=\"$device\"} != 0",
     "legendFormat": "Inverter"
    },
    {
     "expr": "ecoflow_pd_car_temp{device=\"$device\"} != 0",
     "legendFormat": "PD Car"
    },
    {
     "expr": "ecoflow_bms_master_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_temp{device=\"$device\"} != 0",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_bms_master_max_cell_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_max_cell_temp{device=\"$device\"} != 0",
     "legendFormat": "Max Cell"
    },
    {
     "expr": "ecoflow_bms_master_min_cell_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_min_cell_temp{device=\"$device\"} != 0",
     "legendFormat": "Min Cell"
    },
    {
     "expr": "ecoflow_bms_master_max_mos_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_max_mos_temp{device=\"$device\"} != 0",
     "legendFormat": "Max MOS"
    },
    {
     "expr": "ecoflow_bms_master_min_mos_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_min_mos_temp{device=\"$device\"} != 0",
     "legendFormat": "Min MOS"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_amp{device=\"$device\"}",
     "legendFormat": "AC IN Current"
    },
    {
     "expr": "ecoflow_inv_inv_out_amp{device=\"$device\"}",
     "legendFormat": "Inverter OUT Current"
    },
    {
     "expr": "abs(ecoflow_bms_bms_status_amp{device=\"$device\"})",
     "legendFormat": "BMS Current"
    }
   ]
  },
  {
   "title": "USB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_pd_usb1_watts{device=\"$device\"}",
     "legendFormat": "USB"
    },
    {
     "expr": "ecoflow_pd_typec1_watts{device=\"$device\"}",
     "legendFormat": "TypeC"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol{device=\"$device\"} or ecoflow_bms_bms_status_vol{device=\"$device\"}",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_bms_master_min_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_vol{device=\"$device\"}",
     "legendFormat": "MIN Cell"
    },
    {
     "expr": "ecoflow_bms_master_max_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_vol{device=\"$device\"}",
     "legendFormat": "MAX Cell"
    }
   ]
  },
  {
   "title": "MQTT Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "targets": [
    {
     "expr": "rate(ecoflow_mqtt_messages_receive_total{device=\"$device\"}[1m])",
     "legendFormat": "MQTT Messages"
    }
   ]
  }
 ]
}