ssh:
    yubikey_5c: ENC[AES256_GCM,data:81XDN+THELecHbkUk3xh1andqC5cdCDEK5n3ZqXHB8Vw6ywcPYo0KWS0E5w9bej0jp9CXCOQasDxx5wTlMaDwkp5G8PUYL/DhgD10F0rBOy/7JOb9JNWVLNxLPr3uOJg2Hz4qZ8Zu4HKTAv7XnREaX/yOfkpRaQrTWrvBgX3uJyVCvZxTLJa9ce0bWBevptDZzjGltc/UFlGOKhXiU1W88mYYQcQgBsFa9NM4QQqhIeSgymS1Ex8l4XGHivXUa+937QXvy4NVj0Ol9BBjvJtwfpxTQiD/fRVU4y7qdkbMvdQdCeDTkzKui5Q0wrQzS1VNQnxYCNjxBmOO0TqORhcC5geGC8PfNbYWsx3dHJkhIYjP5Fx+i1VXRArW9GYPnfRf/icTQmqNS/0Dj27PtJ2tTgxdvK/euFGb3SMiyXcoI/sMFR26OvbxbR++f2hxk9c65mAkT8eG1Xl3ebRM2qh2Wx/bNpf8uw2CI4f62Z3pCLE302MHTM/D2scBSA2leATkXVsndju3iYafmSLOm+rTg4Z3pases9Taq+XRd1fqIttkREJX/96J1NF8iTrman4UblzPBWB99+MBDndMGfhxSVPMf5F5FoLSArobHG3Kmf/vXRqCoi+6M/hswZxlRexQxDHJLOJ6MW7FeQRYRdEEA==,iv:bpdCu4Si/iF7KAtjxc/UXOhROPBrDe1gv/nbYkORNQg=,tag:WymMReKy/UEtmzZVTwWg2g==,type:str]
    yubikey_5c.pub: ENC[AES256_GCM,data:yR2GYGF2TaqDa6iB1XnAvRPZOZ7nLQumtIGsELAUbhCwoPKwGlhwxl9MjFQHIKWfqDeDAaWHPJTSU8xyBuDOENikEgVVk58vzcVPIP96cP72+jHlRBy+nlVDLaTaxJsxXgRjigKHUNETdMNDgwzU5xXaI3+RmXn1TF73YHzDhe1WLnu/VNBE6i/ZUFeAzswtLSaN32FXwEH0DeArbGNcvOLhrvk4VTUezqs=,iv:o7IHEE9Y6OAXytSP/IksBiaxzsK2oUxvySjgQabcb9E=,tag:u1pzdBB6J/xjpkxkkOVV9g==,type:str]
    yubikey_5c_nano: ENC[AES256_GCM,data:6rm9ZCx6CBOtSeHvhkpTtZ/fu66VL3+Cyt2QcJGxwMPFfxSm6qNYNhwax/0Bh18yREipVCWCt5BakPz/qHKnlFoksiCchDUGNyQNuIDggAWJNM8BAUeC1irCvlTiNmNo8AUq6dYpWewrL5XjN49acywPfX0ssmUqKvPGaaedww3NMIU/u29O5e1xTtq3Q5Up/toUumgAmZD50TTd8TmOBOaOWcPox1IAjyRdszTX3NrjJ9EjEPFj6QzV86MIkVgf5OZeaT4vB/ylBwUr17K2UaEnFl+FzaxQIquRPfvz22U7XyTZWTdw06TQMMjVhBVfvEF9ZByzaLMGC/ACWNN5IgaVyqVLqLm8WT/pU/hwz4hRKU3698cdEjf3BJojFLd/gmyzzIuX/jCmTTqHnW/kEoDZOZp7a5ERPNVljT9sroekeraHMpVAU+3f/vNr15q4nZRbmBstwGznesQEX6/QiGArz9tCJrcpBnEm1bISFVF5p9q3JaV0IxQLqtKZI3RXBYn1YTfeJQHn5PSpdSv1GavrtpBRC5N1jW/nQ8lBKBOIpMHFL7jSLJa9I4g2Ba8ujkrZHi1ibM6F5KPdgPTBsYMLYsDi6V5xw6QgwKERTOlZoJL6B9URLRdIMe7tJZjG7sCbj6DpXKYjl9vGGC4UX3cJCh5gAFvQL3KSV8AAsjjbN2YhnRgHZrTPe87d+ScAhZD3zNc5Q1zW,iv:Amo0J1YPDTZTNK4ZHFgtzIGshnYHYezDWwj7Wm3eGi8=,tag:RfljHt+ei8got+hZUasHag==,type:str]
    yubikey_5c_nano.pub: ENC[AES256_GCM,data:pVp145Dy2ouWjEx0gKEZtUxGMMCUqUC+sAWEQhDpLOpOLjB6qFl27c2b/rsoFagA4aVN7v1YphDr87kf3150iGez8+nlQmqoOLxN3GCNoEpzCkWijeZbwINJDbjLJSaVqxaWzmWP0XSNux4SCmrtsKodmyHNwp55pyH5MCZ49VDNDRSHbSMsxDU/P+ZcRRlmr2LQW3pfYeM+tH6MfAZHkBDO6eRrSgsSm4xkXoH+EpKgFXjkX0FZ,iv:/HP30cSO6Up5utaq384ZP3mUHQYodbee8nxLw10Xp0Q=,tag:1zLlCNo1dCYJC1uiTeDmmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT0piY3pEUDYzcjBrckk1
            VUdXc1NNWGtocGlxKzNNUDVuUjI4NVNxT2hjClRMNS9YR0FUVFRjQkM0L2hDNjd6
            Y0wzUTM5dCtwdTl2U00vWm9JTHZuMncKLS0tIHFEK0hjMkNPMHhMOVBNL1BQTnVx
            aFluMFdZaXcvd2IwcE9vRkpxYkFINjQK9dZF7Fh1dwWPeuOZeBJCQsLk5VS1CrML
            idGsESHJfUeAYnR1yJ92AQ9lE09bYqaS4peyx8SoCcg9qqrvclrA7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mdd7y8q0nfk5gqkxg5jyfnzepdsx8vze9kppr93nz3455cmh3assxzquq0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQXVLVi96NHVYU2hvMDhq
            Slc1ejNSc3FCZXVUSkhsaWhGak5tVGlkNjNVCjNjNkpzcjE2SjBpZzRnekpOTThv
            eCs5WG9mbzBnVVNXUldJTzhDdHlTMEEKLS0tIEQ5NVYvWUd3SE9UNDlTcmhnclJm
            dnpqejU5azdDL1I0SEtZcHNTQUljSjgK0IwHPR90IoGythxE6lfCKtXyQPxTm6/5
            ugBhTmfemv2ihYPessdPd/kNpAR0Fqp5zAnalsnAjZa32/AyluMQgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tx8dfgnfx4ql6wgch6cujyz4czx75k4upwg9udc8af3dgg7wvpvqlj6emp
    lastmodified: "2026-02-22T10:34:29Z"
    mac: ENC[AES256_GCM,data:X38BjYSUC87q/SoOpzWsUQ+7hNBMvxL+hy2iSqcWJkux1Wj92zU972SlrHk0GW9RVGpt+A2zt6h7FmFLmj94kGDtqeG3YIfL0YRN2pzm6ePHaHPE0+E+bWl/28PBd25+2tPEDjh+S6QmZ4R8tF6SolAyE6B4WceV8wfQt4L8VG8=,iv:73AHheXgibd+dvP/kn9MLmDUUKMdxTc55u7V0O8gtRc=,tag:cQrxALGsc4fULeC2S3SI8Q==,type:str]
    pgp:
        - created_at: "2026-07-19T20:52:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWXc/otv8sz4SAQdAkOEqu6t7RW09L3GMebBCpYCBRlzvbocxCGXuulqORkMw
            n6zgNGeY1wpSo4277p1OnxL1ZfE6qo1ekEtW6IgxIlqWFlHul9R5Xb1pgfEFq/y8
            0l4B7jsVVnku9Copuu+YbFhNId4DU5YtPQ6mpcnV/QjSz+i5Y2ycSSP/kwPe/Irc
            ProkhSQ/WXf+ZWd9KqkFmZGI0h5bkwmNWJOABqJV9ztZOR06x9NvopjP9sA2DVlP
            =50xl
            -----END PGP MESSAGE-----
          fp: 4F0758D4AAE24E6D5A4483C666A20525398E18D7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
